package mavo.zuehlkeschindlerapp.SensorData;

import org.json.JSONException;
import org.json.JSONObject;

import mavo.zuehlkeschindlerapp.SensorType;

/**
 *  AccelerometerData.java
 *  AndroidSensorApp
 *
 *  © 2016 Zühlke Engineering AG. All rights reserved.
 *
 *  Models data generated by the accelerometer sensor.
 */
public class AccelerometerData extends AbstractSensorData {

    private String xAcceleration;
    private String yAcceleration;
    private String zAcceleration;

    public AccelerometerData(String xAcceleration, String yAcceleration, String zAcceleration, String timestamp) {
        super(SensorType.ACCELEROMETER, timestamp);
        this.xAcceleration = xAcceleration;
        this.yAcceleration = yAcceleration;
        this.zAcceleration = zAcceleration;
    }

    @Override
    public JSONObject toJSON() throws JSONException {
        JSONObject object = super.toJSON();
        object.put("x", this.xAcceleration);
        object.put("y", this.yAcceleration);
        object.put("z", this.zAcceleration);
        return object;
    }
}