package mavo.zuehlkeschindlerapp.SensorData;

import org.json.JSONException;
import org.json.JSONObject;

import mavo.zuehlkeschindlerapp.SensorType;

/**
 *  BarometerData.java
 *  AndroidSensorApp
 *
 *  © 2016 Zühlke Engineering AG. All rights reserved.
 *
 * Models data generated by the pressure sensor.
 */

public class BarometerData extends AbstractSensorData {

    private String pressureInHPa;

    public BarometerData(String pressure, String timestamp) {
        super(SensorType.BAROMETER, timestamp);
        this.pressureInHPa = pressure;
    }

    @Override
    public JSONObject toJSON() throws JSONException {
        JSONObject object = super.toJSON();
        object.put("pressure", this.pressureInHPa);

        return object;
    }
}

