package mavo.zuehlkeschindlerapp.SensorData;

import org.json.JSONException;
import org.json.JSONObject;

import mavo.zuehlkeschindlerapp.SensorType;

/**
 *  LightSensorData.java
 *  AndroidSensorApp
 *
 *  © 2016 Zühlke Engineering AG. All rights reserved.
 *
 * Models data generated by the ambient light sensor.
 */
public class LightSensorData extends AbstractSensorData {

    private String ambientLevel;

    public LightSensorData(String ambientLevel, String timestamp) {
        super(SensorType.LIGHT, timestamp);
        this.ambientLevel = ambientLevel;
    }

    @Override
    public JSONObject toJSON() throws JSONException {
        JSONObject object = super.toJSON();
        object.put("level", this.ambientLevel);
        return object;
    }
}
