package mavo.zuehlkeschindlerapp.SensorData;

import org.json.JSONException;
import org.json.JSONObject;

import mavo.zuehlkeschindlerapp.SensorType;

/**
 *  LinearAccelerationData.java
 *  AndroidSensorApp
 *
 *  © 2016 Zühlke Engineering AG. All rights reserved.
 *
 * Models data generated by the virtual linear acceleration sensor.
 */

public class LinearAccelerationData extends AbstractSensorData {

    private String xLinearAcceleration;
    private String yLinearAcceleration;
    private String zLinearAcceleration;

    public LinearAccelerationData(String xLinearAcceleration, String yLinearAcceleration, String zLinearAcceleration, String timestamp) {
        super(SensorType.LINEAR_ACCELERATION, timestamp);
        this.xLinearAcceleration = xLinearAcceleration;
        this.yLinearAcceleration = yLinearAcceleration;
        this.zLinearAcceleration = zLinearAcceleration;
    }

    @Override
    public JSONObject toJSON() throws JSONException {
        JSONObject object = super.toJSON();
        object.put("x", this.xLinearAcceleration);
        object.put("y", this.yLinearAcceleration);
        object.put("z", this.zLinearAcceleration);
        return object;
    }
}
