package mavo.zuehlkeschindlerapp.SensorData;

import org.json.JSONException;
import org.json.JSONObject;

import mavo.zuehlkeschindlerapp.SensorData.AbstractSensorData;
import mavo.zuehlkeschindlerapp.SensorType;

/**
 *  MagnetometerData.java
 *  AndroidSensorApp
 *
 *  © 2016 Zühlke Engineering AG. All rights reserved.
 *
 * Models data generated by the magnetic field sensor
 */
public class MagnetometerData extends AbstractSensorData {

    private String xMagneticField;
    private String yMagneticField;
    private String zMagneticField;

    public MagnetometerData(String xMagneticField, String yMagneticField, String zMagneticField, String timestamp) {
        super(SensorType.MAGNETOMETER, timestamp);
        this.xMagneticField = xMagneticField;
        this.yMagneticField = yMagneticField;
        this.zMagneticField = zMagneticField;
    }

    @Override
    public JSONObject toJSON() throws JSONException {
        JSONObject object = super.toJSON();
        object.put("x", this.xMagneticField);
        object.put("y", this.yMagneticField);
        object.put("z", this.zMagneticField);
        return object;
    }
}
