package mavo.zuehlkeschindlerapp.SensorData;

import org.json.JSONException;
import org.json.JSONObject;

import mavo.zuehlkeschindlerapp.SensorType;

/**
 *  TemperatureData.java
 *  AndroidSensorApp
 *
 *  © 2016 Zühlke Engineering AG. All rights reserved.
 *
 * Models data generated by the ambient temperature sensor.
 */
public class TemperatureData extends AbstractSensorData {

    private String temperatureInCelsius;

    public TemperatureData(String temperatureInCelsius, String timestamp) {
        super(SensorType.TEMPERATURE, timestamp);
        this.temperatureInCelsius = temperatureInCelsius;
    }

    @Override
    public JSONObject toJSON() throws JSONException {
        JSONObject object = super.toJSON();
        object.put("temperature", this.temperatureInCelsius);
        return object;
    }
}
